export {
  getRegistrationStatus,
  getSharedContainerPath,
  isSupported,
  registerCredential,
  registerCredentials,
  removeAllCredentials,
  removeCredential,
} from './api'
export { defaultMatcher, matcherProtocols } from './matchers'
export type {
  AndroidDcApiRequest,
  DcApiClaimValue,
  DcApiCredential,
  DcApiCredentialDisplay,
  DcApiMatcher,
  DcApiMdocCredential,
  DcApiProtocol,
  DcApiProtocolRequest,
  DcApiRequest,
  DcApiResponseOptions,
  DcApiSdJwtCredential,
  IosDcApiRequest,
  IosDocumentRequest,
  IosDocumentRequestSet,
  IosPresentmentRequest,
  IosReaderAuthentication,
  IosRequestedElement,
  IosRegistrationOptions,
  IosSupportedDocumentType,
  IsoMdocProtocolRequest,
  IsoMdocResponseOptions,
  Openid4vpProtocol,
  Openid4vpProtocolRequest,
  Openid4vpResponseOptions,
  RegisterCredentialOptions,
  RegisterCredentialsOptions,
  RegistrationStatus,
  SdJwtClaims,
} from './types'
export { dcApiProtocols, iosSupportedDocumentTypes } from './types'
export { DcApiUnsupportedError } from './util'
